## 练习
请编写代码使程序能够运行并且通过测试用例。

将你完成的练习全部运行一遍后，左上角File->Download Notebook。将下载的ipynb文件按照Lab文档要求进行处理，上传到elearning。该部分完成后还有第二部分https://www.kaggle.com/guluguluwulu/pytorch-nn

如果代码中使用了 for 去遍历张量的某个维度，那么这段代码会扣分。Python中的 for 是非常低效的，使用PyTorch张量的目的就是提高计算效率。在大多数情况下，PyTorch提供的接口能让我们避免 for 的使用。

总共五题，每一题25分。做出四题即可满分。多做不加分。

如果遇到困难，可以：
+ 看看前面的基础知识
+ 看看提示
+ 点击提示中给出的pytorch函数链接，去官方文档看看这个函数是怎么使用的。感兴趣的同学可以看看[pytorch官网总文档](https://pytorch.org/docs/stable/index.html)，里面内容较多。
+ 鼓励大家助教群中提问交流，不要抄袭同学

### 创建Tensor
在函数`multiples_of_ten`中创建一个tensor，数据类型是`torch.float64`，包含了从start到stop之间的10的倍数。

提示：[`torch.arange`](https://pytorch.org/docs/stable/generated/torch.arange.html)

In [9]:
import torch

def multiples_of_ten(start: int, stop: int) -> torch.Tensor:
    """
    Returns a Tensor of dtype torch.float64 that contains all of the multiples
    of ten (in order) between start and stop, inclusive. If there are no
    multiples of ten in this range then return an empty tensor of shape (0,).

    Args:
        start: Beginning ot range to create.
        stop: End of range to create (stop >= start).

    Returns:
        x: float64 Tensor giving multiples of ten between start and stop
    """
    assert start <= stop
    low = ((start + 9) // 10) * 10  
    high = (stop // 10) * 10
    if low > high:
        return torch.tensor([], dtype=torch.float64)
    x = torch.arange(low, high + 1, step=10, dtype=torch.float64)
    return x

start = 5
stop = 25
x = multiples_of_ten(start, stop)
print('Correct dtype: ', x.dtype == torch.float64)
print('Correct shape: ', x.shape == (2,))
print('Correct values: ', x.tolist() == [10, 20])

# If there are no multiples of ten in the given range you should return an empty tensor
start = 5
stop = 7
x = multiples_of_ten(start, stop)
print('\nCorrect dtype: ', x.dtype == torch.float64)
print('Correct shape: ', x.shape == (0,))

Correct dtype:  True
Correct shape:  True
Correct values:  True

Correct dtype:  True
Correct shape:  True


### 索引
实现`slice_assignment_practice`函数，使输出的张量与`expected`相同，同时有如下限制：
+ 只能使用切片索引的方式对x进行赋值
+ 只能使用<=6次赋值

In [5]:
import torch

def slice_assignment_practice(x: torch.Tensor) -> torch.Tensor:
    """
    Given a two-dimensional tensor of shape (M, N) with M >= 4, N >= 6, mutate
    its first 4 rows and 6 columns so they are equal to:

    [0 1 2 2 2 2]
    [0 1 2 2 2 2]
    [3 4 3 4 5 5]
    [3 4 3 4 5 5]

    Note: the input tensor shape is not fixed to (4, 6).

    Your implementation must obey the following:
    - You should mutate the tensor x in-place and return it
    - You should only modify the first 4 rows and first 6 columns; all other
      elements should remain unchanged
    - You may only mutate the tensor using slice assignment operations, where
      you assign an integer to a slice of the tensor
    - You must use <= 6 slicing operations to achieve the desired result

    Args:
        x: A tensor of shape (M, N) with M >= 4 and N >= 6

    Returns:
        x
    """
    
    x[0:2,[0]] = 0
    x[0:2,[1]] = 1
    x[0:2,2:6] = 2
    x[2:4,[0,2]] = 3
    x[2:4,[1,3]] = 4
    x[2:4,4:6] = 5
    return x

# note: this "x" has one extra row, intentionally
x = torch.zeros(5, 7, dtype=torch.int64)
print('Here is x before calling slice_assignment_practice:')
print(x)
slice_assignment_practice(x)
print('Here is x after calling slice assignment practice:')
print(x)

expected = [
    [0, 1, 2, 2, 2, 2, 0],
    [0, 1, 2, 2, 2, 2, 0],
    [3, 4, 3, 4, 5, 5, 0],
    [3, 4, 3, 4, 5, 5, 0],
    [0, 0, 0, 0, 0, 0, 0],
]
print('Correct: ', x.tolist() == expected)

Here is x before calling slice_assignment_practice:
tensor([[0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0]])
Here is x after calling slice assignment practice:
tensor([[0, 1, 2, 2, 2, 2, 0],
        [0, 1, 2, 2, 2, 2, 0],
        [3, 4, 3, 4, 5, 5, 0],
        [3, 4, 3, 4, 5, 5, 0],
        [0, 0, 0, 0, 0, 0, 0]])
Correct:  True


### 形状操作
实现函数`reshape_practice`使输出和`expected`相同。

提示：使用 .view() 以及[torch.cat](https://pytorch.org/docs/stable/generated/torch.cat.html)。这题有一定难度，同学可以先观察y中连续的部分，使用 .view() 将x转化为类似的形状。随后使用切片的方式切出两个部分。最后把两个部分利用cat函数拼接。

在这个过程中同学可以输出一些中间值观察一下，便于理解和debug。

In [10]:
import torch

def reshape_practice(x: torch.Tensor) -> torch.Tensor:
    """
    Given an input tensor of shape (24,), return a reshaped tensor y of shape
    (3, 8) such that

    y = [[x[0], x[1], x[2],  x[3],  x[12], x[13], x[14], x[15]],
         [x[4], x[5], x[6],  x[7],  x[16], x[17], x[18], x[19]],
         [x[8], x[9], x[10], x[11], x[20], x[21], x[22], x[23]]]

    You must construct y by performing a sequence of reshaping operations on
    x (view, t, transpose, permute, contiguous, reshape, etc). The input
    tensor should not be modified.

    Args:
        x: A tensor of shape (24,)

    Returns:
        y: A reshaped version of x of shape (3, 8) as described above.
    """
    y = x.clone().view(3,8)
    y_clone = y.clone()
    y_clone[0,4:] = y[1,4:]
    y_clone[1,0:4] = y[0,4:]
    y_clone[1,4:] = y[2,0:4]
    y_clone[2,0:4] = y[1,0:4]
    return y_clone

x = torch.arange(24)
print('Here is x:')
print(x)
y = reshape_practice(x)
print('Here is y:')
print(y)

expected = [
    [0, 1,  2,  3, 12, 13, 14, 15],
    [4, 5,  6,  7, 16, 17, 18, 19],
    [8, 9, 10, 11, 20, 21, 22, 23]]
print('Correct:', y.tolist() == expected)

Here is x:
tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23])
Here is y:
tensor([[ 0,  1,  2,  3, 12, 13, 14, 15],
        [ 4,  5,  6,  7, 16, 17, 18, 19],
        [ 8,  9, 10, 11, 20, 21, 22, 23]])
Correct: True


### 聚合运算
实现函数`normalize_columns`，该函数对矩阵的列做normalize操作。

```
x = [[ 0,  30,  600],
     [ 1,  10,  200],
     [-1,  20,  400]]
```
- 第一列均值 0、 标准差 1
- 第二列均值 20、 标准差 10
- 第三列均值 400、 标准差 200

```
y = [[ 0,  1,  1],
     [ 1, -1, -1],
     [-1,  0,  0]]
```

如果某一列为 $x_1,\ldots,x_M$、均值 $\mu$、标准差 $\sigma$，则

$$\mu=\frac{1}{M}\sum_{i=1}^M x_i \hspace{4pc} \sigma = \sqrt{\frac{1}{M-1}\sum_{i=1}^M(x_i-\mu)^2}$$

归一化后的结果为$$y_i=\frac{x_i-\mu}{\sigma}$$

In [12]:
import torch

def normalize_columns(x: torch.Tensor) -> torch.Tensor:
    """
    Normalize the columns of the matrix x by subtracting the mean and dividing
    by standard deviation of each column. You should return a new tensor; the
    input should not be modified.

    More concretely, given an input tensor x of shape (M, N), produce an output
    tensor y of shape (M, N) where y[i, j] = (x[i, j] - mu_j) / sigma_j, where
    mu_j is the mean of the column x[:, j].

    Your implementation should not use any explicit Python loops (including
    comprehensions); you may only use basic arithmetic operations on tensors
    (+, -, *, /, **, sqrt), the sum reduction function, and reshape operations
    to facilitate broadcasting. You should not use torch.mean, torch.std, or
    their instance method variants x.mean, x.std.

    Args:
        x: Tensor of shape (M, N).

    Returns:
        y: Tensor of shape (M, N) as described above. It should have the same
            dtype as the input x.
    """
    mu = x.sum(dim=0) / x.size(0)
    var = (x - mu) ** 2
    mean = var.sum(dim=0) / (x.size(0) - 1)
    sigma = mean ** 0.5 
    y = (x - mu) / sigma

    return y

x = torch.tensor([[0., 30., 600.], [1., 10., 200.], [-1., 20., 400.]])
y = normalize_columns(x)
print('Here is x:')
print(x)
print('Here is y:')
print(y)

x_expected = [[0., 30., 600.], [1., 10., 200.], [-1., 20., 400.]]
y_expected = [[0., 1., 1.], [1., -1., -1.], [-1., 0., 0.]]
y_correct = y.tolist() == y_expected
x_correct = x.tolist() == x_expected
print('y correct: ', y_correct)
print('x unchanged: ', x_correct)

Here is x:
tensor([[  0.,  30., 600.],
        [  1.,  10., 200.],
        [ -1.,  20., 400.]])
Here is y:
tensor([[ 0.,  1.,  1.],
        [ 1., -1., -1.],
        [-1.,  0.,  0.]])
y correct:  True
x unchanged:  True


### 聚合、索引赋值

在不用for循环的情况下，使用reduction和indexing操作，把张量每一行最小的元素设置为0.

提示：在这题中，同学需要先找出最小值所在的位置。随后利用这个位置进行索引+赋值操作。

In [13]:
import torch

def zero_row_min(x: torch.Tensor) -> torch.Tensor:
    """
    Return a copy of the input tensor x, where the minimum value along each row
    has been set to 0.

    For example, if x is:
    x = torch.tensor([
          [10, 20, 30],
          [ 2,  5,  1]])

    Then y = zero_row_min(x) should be:
    torch.tensor([
        [0, 20, 30],
        [2,  5,  0]
    ])

    Your implementation should use reduction and indexing operations. You should
    not use any Python loops (including comprehensions). The input tensor
    should not be modified.

    Args:
        x: Tensor of shape (M, N)

    Returns:
        y: Tensor of shape (M, N) that is a copy of x, except the minimum value
            along each row is replaced with 0.
    """
    y = x.clone()
    min_indices = torch.argmin(y, dim=1)
    y[range(y.shape[0]), min_indices] = 0
    return y

x0 = torch.tensor([[10, 20, 30], [2, 5, 1]])
print('Here is x0:')
print(x0)
y0 = zero_row_min(x0)
print('Here is y0:')
print(y0)
expected = [[0, 20, 30], [2, 5, 0]]
y0_correct = torch.is_tensor(y0) and y0.tolist() == expected
print('y0 correct: ', y0_correct)

x1 = torch.tensor([[2, 5, 10, -1], [1, 3, 2, 4], [5, 6, 2, 10]])
print('\nHere is x1:')
print(x1)
y1 = zero_row_min(x1)
print('Here is y1:')
print(y1)
expected = [[2, 5, 10, 0], [0, 3, 2, 4], [5, 6, 0, 10]]
y1_correct = torch.is_tensor(y1) and y1.tolist() == expected
print('y1 correct: ', y1_correct)

Here is x0:
tensor([[10, 20, 30],
        [ 2,  5,  1]])
Here is y0:
tensor([[ 0, 20, 30],
        [ 2,  5,  0]])
y0 correct:  True

Here is x1:
tensor([[ 2,  5, 10, -1],
        [ 1,  3,  2,  4],
        [ 5,  6,  2, 10]])
Here is y1:
tensor([[ 2,  5, 10,  0],
        [ 0,  3,  2,  4],
        [ 5,  6,  0, 10]])
y1 correct:  True
